spring.application.name=apiRestTpte
spring.datasource.url=jdbc:mysql://${HOST_DB}:${PORT_DB}/lognc?useSSL=false
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
server.port=${PORT_SERVER}

